# Form implementation generated from reading ui file 'EasyAcct_BalEditor.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BalEditor(object):
    def setupUi(self, BalEditor):
        BalEditor.setObjectName("BalEditor")
        BalEditor.resize(319, 271)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=BalEditor)
        self.buttonBox.setGeometry(QtCore.QRect(-30, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.t_accountname = QtWidgets.QLineEdit(parent=BalEditor)
        self.t_accountname.setGeometry(QtCore.QRect(80, 10, 231, 23))
        self.t_accountname.setReadOnly(True)
        self.t_accountname.setObjectName("t_accountname")
        self.label = QtWidgets.QLabel(parent=BalEditor)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.t_accounttype = QtWidgets.QLineEdit(parent=BalEditor)
        self.t_accounttype.setGeometry(QtCore.QRect(80, 40, 231, 23))
        self.t_accounttype.setReadOnly(True)
        self.t_accounttype.setObjectName("t_accounttype")
        self.label_2 = QtWidgets.QLabel(parent=BalEditor)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(parent=BalEditor)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 301, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 101, 51))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 20, 121, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_deposit = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_deposit.setObjectName("rb_deposit")
        self.verticalLayout.addWidget(self.rb_deposit)
        self.rb_withdraw = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_withdraw.setObjectName("rb_withdraw")
        self.verticalLayout.addWidget(self.rb_withdraw)
        self.box_amount = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.box_amount.setGeometry(QtCore.QRect(50, 100, 191, 31))
        self.box_amount.setObjectName("box_amount")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(53, 80, 191, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(BalEditor)
        self.buttonBox.accepted.connect(BalEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(BalEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BalEditor)

    def retranslateUi(self, BalEditor):
        _translate = QtCore.QCoreApplication.translate
        BalEditor.setWindowTitle(_translate("BalEditor", "New Transaction"))
        self.label.setText(_translate("BalEditor", "Account"))
        self.label_2.setText(_translate("BalEditor", "Type"))
        self.groupBox.setTitle(_translate("BalEditor", "Transaction"))
        self.label_3.setText(_translate("BalEditor", "Transaction Type"))
        self.rb_deposit.setText(_translate("BalEditor", "Deposit"))
        self.rb_withdraw.setText(_translate("BalEditor", "Withdraw"))
        self.label_4.setText(_translate("BalEditor", "Amount"))
