# Form implementation generated from reading ui file 'EasyAcct_ConnDialogBox.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 260, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.b_testConn = QtWidgets.QPushButton(parent=Dialog)
        self.b_testConn.setGeometry(QtCore.QRect(10, 260, 131, 31))
        self.b_testConn.setObjectName("b_testConn")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 321, 80))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.label.setObjectName("label")
        self.conn_addr = QtWidgets.QLineEdit(parent=self.groupBox)
        self.conn_addr.setGeometry(QtCore.QRect(10, 40, 241, 23))
        self.conn_addr.setObjectName("conn_addr")
        self.conn_port = QtWidgets.QLineEdit(parent=self.groupBox)
        self.conn_port.setGeometry(QtCore.QRect(260, 40, 51, 23))
        self.conn_port.setObjectName("conn_port")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 54, 17))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 90, 361, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 17))
        self.label_4.setObjectName("label_4")
        self.conn_uname = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.conn_uname.setGeometry(QtCore.QRect(10, 40, 251, 23))
        self.conn_uname.setObjectName("conn_uname")
        self.conn_pass = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.conn_pass.setGeometry(QtCore.QRect(10, 90, 251, 23))
        self.conn_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.conn_pass.setObjectName("conn_pass")
        self.conn_b_showpassword = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.conn_b_showpassword.setGeometry(QtCore.QRect(270, 86, 77, 31))
        self.conn_b_showpassword.setCheckable(True)
        self.conn_b_showpassword.setObjectName("conn_b_showpassword")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 371, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Connection Manager"))
        self.b_testConn.setText(_translate("Dialog", "Test Connection..."))
        self.groupBox.setTitle(_translate("Dialog", "Connection URL"))
        self.label.setText(_translate("Dialog", "Database Address"))
        self.conn_addr.setText(_translate("Dialog", "localhost"))
        self.conn_port.setText(_translate("Dialog", "3306"))
        self.label_2.setText(_translate("Dialog", "Port"))
        self.groupBox_2.setTitle(_translate("Dialog", "Authentication"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.conn_b_showpassword.setText(_translate("Dialog", "View"))
        self.label_5.setText(_translate("Dialog", "Connection Not Established"))
