# Form implementation generated from reading ui file 'EasyAcct_Transhistory.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TransHistory(object):
    def setupUi(self, TransHistory):
        TransHistory.setObjectName("TransHistory")
        TransHistory.resize(517, 440)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=TransHistory)
        self.buttonBox.setGeometry(QtCore.QRect(160, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=TransHistory)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 381))
        self.groupBox.setObjectName("groupBox")
        self.tableView = QtWidgets.QTableView(parent=self.groupBox)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 471, 351))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(parent=TransHistory)
        self.pushButton.setGeometry(QtCore.QRect(10, 400, 77, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(TransHistory)
        self.buttonBox.accepted.connect(TransHistory.accept) # type: ignore
        self.buttonBox.rejected.connect(TransHistory.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TransHistory)

    def retranslateUi(self, TransHistory):
        _translate = QtCore.QCoreApplication.translate
        TransHistory.setWindowTitle(_translate("TransHistory", "Transaction History"))
        self.groupBox.setTitle(_translate("TransHistory", "Transaction History for Account"))
        self.pushButton.setText(_translate("TransHistory", "Refresh"))
