# Form implementation generated from reading ui file 'EasyAcct_AcctEditor.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AccountEditor(object):
    def setupUi(self, AccountEditor):
        AccountEditor.setObjectName("AccountEditor")
        AccountEditor.resize(246, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AccountEditor)
        self.buttonBox.setGeometry(QtCore.QRect(-140, 260, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=AccountEditor)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 241))
        self.groupBox.setObjectName("groupBox")
        self.accountName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.accountName.setGeometry(QtCore.QRect(10, 40, 211, 23))
        self.accountName.setObjectName("accountName")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 191, 17))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 211, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_savings = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_savings.setObjectName("rb_savings")
        self.verticalLayout.addWidget(self.rb_savings)
        self.rb_acct = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_acct.setObjectName("rb_acct")
        self.verticalLayout.addWidget(self.rb_acct)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 81, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 101, 17))
        self.label_3.setObjectName("label_3")
        self.balance = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.balance.setGeometry(QtCore.QRect(10, 200, 211, 31))
        self.balance.setMaximum(999999999999.99)
        self.balance.setObjectName("balance")

        self.retranslateUi(AccountEditor)
        self.buttonBox.accepted.connect(AccountEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(AccountEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AccountEditor)

    def retranslateUi(self, AccountEditor):
        _translate = QtCore.QCoreApplication.translate
        AccountEditor.setWindowTitle(_translate("AccountEditor", "Account Editor"))
        self.groupBox.setTitle(_translate("AccountEditor", "Edit Account..."))
        self.label.setText(_translate("AccountEditor", "Account Name (Must be Unique)"))
        self.rb_savings.setText(_translate("AccountEditor", "Default Account Type"))
        self.rb_acct.setText(_translate("AccountEditor", "Savings Account"))
        self.label_2.setText(_translate("AccountEditor", "Account Type"))
        self.label_3.setText(_translate("AccountEditor", "Balance"))
