# Form implementation generated from reading ui file 'EasyAcct_ConnHub.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnMgr(object):
    def setupUi(self, ConnMgr):
        ConnMgr.setObjectName("ConnMgr")
        ConnMgr.resize(421, 232)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConnMgr)
        self.buttonBox.setGeometry(QtCore.QRect(250, 200, 151, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.connList = QtWidgets.QListView(parent=ConnMgr)
        self.connList.setGeometry(QtCore.QRect(10, 30, 311, 161))
        self.connList.setObjectName("connList")
        self.label = QtWidgets.QLabel(parent=ConnMgr)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label.setObjectName("label")
        self.b_New = QtWidgets.QPushButton(parent=ConnMgr)
        self.b_New.setGeometry(QtCore.QRect(330, 50, 81, 20))
        self.b_New.setObjectName("b_New")
        self.b_Edit = QtWidgets.QPushButton(parent=ConnMgr)
        self.b_Edit.setGeometry(QtCore.QRect(330, 80, 81, 20))
        self.b_Edit.setObjectName("b_Edit")
        self.b_Select = QtWidgets.QPushButton(parent=ConnMgr)
        self.b_Select.setGeometry(QtCore.QRect(330, 110, 81, 20))
        self.b_Select.setObjectName("b_Select")
        self.b_delete = QtWidgets.QPushButton(parent=ConnMgr)
        self.b_delete.setGeometry(QtCore.QRect(330, 140, 81, 20))
        self.b_delete.setObjectName("b_delete")

        self.retranslateUi(ConnMgr)
        self.buttonBox.accepted.connect(ConnMgr.accept) # type: ignore
        self.buttonBox.rejected.connect(ConnMgr.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConnMgr)

    def retranslateUi(self, ConnMgr):
        _translate = QtCore.QCoreApplication.translate
        ConnMgr.setWindowTitle(_translate("ConnMgr", "Database Connections"))
        self.label.setText(_translate("ConnMgr", "Connections"))
        self.b_New.setText(_translate("ConnMgr", "Add New..."))
        self.b_Edit.setText(_translate("ConnMgr", "Edit..."))
        self.b_Select.setText(_translate("ConnMgr", "Set Active"))
        self.b_delete.setText(_translate("ConnMgr", "Delete"))
